image: docker:24.0.5

services:
  - docker:24.0.5-dind

stages:
  - build
  # - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

# test:
#   stage: test
#   script:
#     - docker-compose -f docker-compose.yml up -d
#     - echo "Aguardando inicialização dos serviços..."
#     - sleep 15 # Aguarda os serviços inicializarem
#     - docker logs igdocapijsb-app-1 # Exibe logs do contêiner para debug
#     - docker ps | grep app # Verifica se o contêiner está rodando
#     - curl -f http://localhost:8080/actuator/health || (echo "A aplicação falhou nos testes!" && exit 1)

deploy:
  stage: deploy
  script:
    - echo "A imagem foi criada e enviada para o registro com sucesso!"
